services:
  api:
    build:
      context: ./api
      target: development
    command: ["npm", "run", "dev"]
    container_name: ultri-api
    ports:
      - '3000:3000'
    env_file: .env-dev
    volumes:
      - './api/plugins:/usr/src/api/plugins'
      - './api/routes:/usr/src/api/routes'
      - './api/app.js:/usr/src/api/app.js'
    depends_on: 
      - postgres

  postgres:
    build:
      target: development
    container_name: postgres-ultri-izzup
    hostname: postgres
    image: 'postgres:14'
    ports:
      - '5432:5432'
    restart: always
    env_file: .env-dev
    volumes:
      - data_volume:/var/lib/postgres/data

  webapp:
    build:
      context: ./webapp
      target: development
    command: ["quasar", "dev"]
    container_name: izzup-webapp
    ports:
      - '9000:9000'
    env_file: .env-dev
    volumes:
      - './webapp/src:/usr/src/webapp/src'
      - './webapp/public:/usr/src/webapp/public'
    depends_on: 
      - api
    
  ssl-proxy:
    image: openresty/openresty:1.21.4.1-0-jammy
    container_name: ultri-ssl-proxy
    restart: on-failure
    ports:
    - "80:80"
    - "443:443"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    build:
      target: development
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev
    environment:
      # Uncomment to customise these settings

      #Specifies the virtual path from web server root where SMTP4DEV web interface will be hosted. e.g. "/" or "/smtp4dev"
      #- ServerOptions__BasePath=/smtp4dev

      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=devmail.izzup.local

      #Locks settings from being changed by user via web interface
      #- ServerOptions__LockSettings=true

      #Specifies the path where the database will be stored relative to APPDATA env var on Windows or XDG_CONFIG_HOME on non-Windows. Specify "" to use an in memory database.
      #- ServerOptions__Database=database.db

      #Specifies the number of messages to keep
      #- ServerOptions__NumberOfMessagesToKeep=100

      #Specifies the number of sessions to keep
      #- ServerOptions__NumberOfSessionsToKeep=100

      #Specifies the TLS mode to use. None=Off. StartTls=On demand if client supports STARTTLS. ImplicitTls=TLS as soon as connection is established.
      #- ServerOptions__TlsMode=None

      #Specifies the TLS certificate to use if TLS is enabled/requested. Specify "" to use an auto-generated self-signed certificate (then see console output on first startup)
      #- ServerOptions__TlsCertificate=

      #Sets the name of the SMTP server that will be used to relay messages or "" if messages should not be relayed
      #- RelayOptions__SmtpServer=

      #Sets the port number for the SMTP server used to relay messages.
      #- RelayOptions__SmtpPort=25

      #Specifies a comma separated list of recipient addresses for which messages will be relayed. An empty list means that no messages are relayed.
      #- RelayOptions__AllowedEmailsString=

      #Specifies the address used in MAIL FROM when relaying messages. (Sender address in message headers is left unmodified). The sender of each message is used if not specified.
      #- RelayOptions__SenderAddress=

      #The username for the SMTP server used to relay messages. If "" no authentication is attempted.
      #- RelayOptions__Login=

      #The password for the SMTP server used to relay messages
      #- RelayOptions__Password=

      #Specifies the port the IMAP server will listen on - allows standard email clients to view/retrieve messages
      #"ServerOptions__ImapPort"=143

volumes:
  smtp4dev-data: {}
  data_volume: {}

